// flow-typed signature: b75367d0abe724745b2bc2822c20c5a8
// flow-typed version: <<STUB>>/@types/jest_v^23.1.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
